/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EducationRouteImport } from './routes/education'
import { Route as CopyTradingRouteImport } from './routes/copy-trading'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsSymbolRouteImport } from './routes/markets.$symbol'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalUpdatesRouteImport } from './routes/_authenticated/portal.updates'
import { Route as AuthenticatedPortalTransactionsRouteImport } from './routes/_authenticated/portal.transactions'
import { Route as AuthenticatedPortalTradingRouteImport } from './routes/_authenticated/portal.trading'
import { Route as AuthenticatedPortalSupportRouteImport } from './routes/_authenticated/portal.support'
import { Route as AuthenticatedPortalStatementsRouteImport } from './routes/_authenticated/portal.statements'
import { Route as AuthenticatedPortalSettingsRouteImport } from './routes/_authenticated/portal.settings'
import { Route as AuthenticatedPortalReferralsRouteImport } from './routes/_authenticated/portal.referrals'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPortalPortfolioRouteImport } from './routes/_authenticated/portal.portfolio'
import { Route as AuthenticatedPortalPerformanceRouteImport } from './routes/_authenticated/portal.performance'
import { Route as AuthenticatedPortalNotificationsRouteImport } from './routes/_authenticated/portal.notifications'
import { Route as AuthenticatedPortalMfaRouteImport } from './routes/_authenticated/portal.mfa'
import { Route as AuthenticatedPortalFavoritesRouteImport } from './routes/_authenticated/portal.favorites'
import { Route as AuthenticatedPortalDownloadsRouteImport } from './routes/_authenticated/portal.downloads'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal.documents'
import { Route as AuthenticatedPortalCompetitionsRouteImport } from './routes/_authenticated/portal.competitions'
import { Route as AuthenticatedPortalActivityRouteImport } from './routes/_authenticated/portal.activity'
import { Route as AuthenticatedPortalAccountsRouteImport } from './routes/_authenticated/portal.accounts'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppPortfolioRouteImport } from './routes/_authenticated/app.portfolio'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app.activity'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksBinancePayRouteImport } from './routes/api/public/webhooks/binance-pay'
import { Route as AuthenticatedCompetitionsIdTradeRouteImport } from './routes/_authenticated/competitions.$id.trade'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminUserRolesRouteImport } from './routes/_authenticated/_admin/admin.user-roles'
import { Route as AuthenticatedAdminAdminSupportRouteImport } from './routes/_authenticated/_admin/admin.support'
import { Route as AuthenticatedAdminAdminSubscriptionsRouteImport } from './routes/_authenticated/_admin/admin.subscriptions'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin.settings'
import { Route as AuthenticatedAdminAdminSearchRouteImport } from './routes/_authenticated/_admin/admin.search'
import { Route as AuthenticatedAdminAdminRolesRouteImport } from './routes/_authenticated/_admin/admin.roles'
import { Route as AuthenticatedAdminAdminPaymentsRouteImport } from './routes/_authenticated/_admin/admin.payments'
import { Route as AuthenticatedAdminAdminPartnersRouteImport } from './routes/_authenticated/_admin/admin.partners'
import { Route as AuthenticatedAdminAdminOrganizationsRouteImport } from './routes/_authenticated/_admin/admin.organizations'
import { Route as AuthenticatedAdminAdminNotificationsRouteImport } from './routes/_authenticated/_admin/admin.notifications'
import { Route as AuthenticatedAdminAdminMonitoringRouteImport } from './routes/_authenticated/_admin/admin.monitoring'
import { Route as AuthenticatedAdminAdminMarketingRouteImport } from './routes/_authenticated/_admin/admin.marketing'
import { Route as AuthenticatedAdminAdminLiveChatRouteImport } from './routes/_authenticated/_admin/admin.live-chat'
import { Route as AuthenticatedAdminAdminKycRouteImport } from './routes/_authenticated/_admin/admin.kyc'
import { Route as AuthenticatedAdminAdminInvoicesRouteImport } from './routes/_authenticated/_admin/admin.invoices'
import { Route as AuthenticatedAdminAdminFinanceRouteImport } from './routes/_authenticated/_admin/admin.finance'
import { Route as AuthenticatedAdminAdminBackupsRouteImport } from './routes/_authenticated/_admin/admin.backups'
import { Route as AuthenticatedAdminAdminAuditRouteImport } from './routes/_authenticated/_admin/admin.audit'
import { Route as AuthenticatedAdminAdminAnalyticsRouteImport } from './routes/_authenticated/_admin/admin.analytics'
import { Route as AuthenticatedAdminAdminAccountingRouteImport } from './routes/_authenticated/_admin/admin.accounting'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTradingRoute = CopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSymbolRoute = MarketsSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => MarketsRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalUpdatesRoute =
  AuthenticatedPortalUpdatesRouteImport.update({
    id: '/portal/updates',
    path: '/portal/updates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalTransactionsRoute =
  AuthenticatedPortalTransactionsRouteImport.update({
    id: '/portal/transactions',
    path: '/portal/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalTradingRoute =
  AuthenticatedPortalTradingRouteImport.update({
    id: '/portal/trading',
    path: '/portal/trading',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalSupportRoute =
  AuthenticatedPortalSupportRouteImport.update({
    id: '/portal/support',
    path: '/portal/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStatementsRoute =
  AuthenticatedPortalStatementsRouteImport.update({
    id: '/portal/statements',
    path: '/portal/statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalSettingsRoute =
  AuthenticatedPortalSettingsRouteImport.update({
    id: '/portal/settings',
    path: '/portal/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalReferralsRoute =
  AuthenticatedPortalReferralsRouteImport.update({
    id: '/portal/referrals',
    path: '/portal/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/portal/profile',
    path: '/portal/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPortfolioRoute =
  AuthenticatedPortalPortfolioRouteImport.update({
    id: '/portal/portfolio',
    path: '/portal/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalPerformanceRoute =
  AuthenticatedPortalPerformanceRouteImport.update({
    id: '/portal/performance',
    path: '/portal/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalNotificationsRoute =
  AuthenticatedPortalNotificationsRouteImport.update({
    id: '/portal/notifications',
    path: '/portal/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalMfaRoute = AuthenticatedPortalMfaRouteImport.update({
  id: '/portal/mfa',
  path: '/portal/mfa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalFavoritesRoute =
  AuthenticatedPortalFavoritesRouteImport.update({
    id: '/portal/favorites',
    path: '/portal/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalDownloadsRoute =
  AuthenticatedPortalDownloadsRouteImport.update({
    id: '/portal/downloads',
    path: '/portal/downloads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/portal/documents',
    path: '/portal/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalCompetitionsRoute =
  AuthenticatedPortalCompetitionsRouteImport.update({
    id: '/portal/competitions',
    path: '/portal/competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalActivityRoute =
  AuthenticatedPortalActivityRouteImport.update({
    id: '/portal/activity',
    path: '/portal/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAccountsRoute =
  AuthenticatedPortalAccountsRouteImport.update({
    id: '/portal/accounts',
    path: '/portal/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPortfolioRoute =
  AuthenticatedAppPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBinancePayRoute =
  ApiPublicWebhooksBinancePayRouteImport.update({
    id: '/api/public/webhooks/binance-pay',
    path: '/api/public/webhooks/binance-pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCompetitionsIdTradeRoute =
  AuthenticatedCompetitionsIdTradeRouteImport.update({
    id: '/competitions/$id/trade',
    path: '/competitions/$id/trade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminUserRolesRoute =
  AuthenticatedAdminAdminUserRolesRouteImport.update({
    id: '/admin/user-roles',
    path: '/admin/user-roles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSupportRoute =
  AuthenticatedAdminAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSubscriptionsRoute =
  AuthenticatedAdminAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminSearchRoute =
  AuthenticatedAdminAdminSearchRouteImport.update({
    id: '/admin/search',
    path: '/admin/search',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRolesRoute =
  AuthenticatedAdminAdminRolesRouteImport.update({
    id: '/admin/roles',
    path: '/admin/roles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPaymentsRoute =
  AuthenticatedAdminAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminPartnersRoute =
  AuthenticatedAdminAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminOrganizationsRoute =
  AuthenticatedAdminAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsRoute =
  AuthenticatedAdminAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminMonitoringRoute =
  AuthenticatedAdminAdminMonitoringRouteImport.update({
    id: '/admin/monitoring',
    path: '/admin/monitoring',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminMarketingRoute =
  AuthenticatedAdminAdminMarketingRouteImport.update({
    id: '/admin/marketing',
    path: '/admin/marketing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminLiveChatRoute =
  AuthenticatedAdminAdminLiveChatRouteImport.update({
    id: '/admin/live-chat',
    path: '/admin/live-chat',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminKycRoute =
  AuthenticatedAdminAdminKycRouteImport.update({
    id: '/admin/kyc',
    path: '/admin/kyc',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminInvoicesRoute =
  AuthenticatedAdminAdminInvoicesRouteImport.update({
    id: '/admin/invoices',
    path: '/admin/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminFinanceRoute =
  AuthenticatedAdminAdminFinanceRouteImport.update({
    id: '/admin/finance',
    path: '/admin/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminBackupsRoute =
  AuthenticatedAdminAdminBackupsRouteImport.update({
    id: '/admin/backups',
    path: '/admin/backups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAuditRoute =
  AuthenticatedAdminAdminAuditRouteImport.update({
    id: '/admin/audit',
    path: '/admin/audit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAnalyticsRoute =
  AuthenticatedAdminAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminAccountingRoute =
  AuthenticatedAdminAdminAccountingRouteImport.update({
    id: '/admin/accounting',
    path: '/admin/accounting',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRouteWithChildren
  '/portfolios': typeof PortfoliosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/portal/accounts': typeof AuthenticatedPortalAccountsRoute
  '/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/portal/competitions': typeof AuthenticatedPortalCompetitionsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/portal/favorites': typeof AuthenticatedPortalFavoritesRoute
  '/portal/mfa': typeof AuthenticatedPortalMfaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/portfolio': typeof AuthenticatedPortalPortfolioRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/trading': typeof AuthenticatedPortalTradingRoute
  '/portal/transactions': typeof AuthenticatedPortalTransactionsRoute
  '/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/accounting': typeof AuthenticatedAdminAdminAccountingRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/admin/finance': typeof AuthenticatedAdminAdminFinanceRoute
  '/admin/invoices': typeof AuthenticatedAdminAdminInvoicesRoute
  '/admin/kyc': typeof AuthenticatedAdminAdminKycRoute
  '/admin/live-chat': typeof AuthenticatedAdminAdminLiveChatRoute
  '/admin/marketing': typeof AuthenticatedAdminAdminMarketingRoute
  '/admin/monitoring': typeof AuthenticatedAdminAdminMonitoringRoute
  '/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/partners': typeof AuthenticatedAdminAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/search': typeof AuthenticatedAdminAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminAdminSupportRoute
  '/admin/user-roles': typeof AuthenticatedAdminAdminUserRolesRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/competitions/$id/trade': typeof AuthenticatedCompetitionsIdTradeRoute
  '/api/public/webhooks/binance-pay': typeof ApiPublicWebhooksBinancePayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRouteWithChildren
  '/portfolios': typeof PortfoliosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/portal/accounts': typeof AuthenticatedPortalAccountsRoute
  '/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/portal/competitions': typeof AuthenticatedPortalCompetitionsRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/portal/favorites': typeof AuthenticatedPortalFavoritesRoute
  '/portal/mfa': typeof AuthenticatedPortalMfaRoute
  '/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/portal/portfolio': typeof AuthenticatedPortalPortfolioRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/portal/support': typeof AuthenticatedPortalSupportRoute
  '/portal/trading': typeof AuthenticatedPortalTradingRoute
  '/portal/transactions': typeof AuthenticatedPortalTransactionsRoute
  '/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/accounting': typeof AuthenticatedAdminAdminAccountingRoute
  '/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/admin/finance': typeof AuthenticatedAdminAdminFinanceRoute
  '/admin/invoices': typeof AuthenticatedAdminAdminInvoicesRoute
  '/admin/kyc': typeof AuthenticatedAdminAdminKycRoute
  '/admin/live-chat': typeof AuthenticatedAdminAdminLiveChatRoute
  '/admin/marketing': typeof AuthenticatedAdminAdminMarketingRoute
  '/admin/monitoring': typeof AuthenticatedAdminAdminMonitoringRoute
  '/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/admin/partners': typeof AuthenticatedAdminAdminPartnersRoute
  '/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/admin/search': typeof AuthenticatedAdminAdminSearchRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminAdminSupportRoute
  '/admin/user-roles': typeof AuthenticatedAdminAdminUserRolesRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/competitions/$id/trade': typeof AuthenticatedCompetitionsIdTradeRoute
  '/api/public/webhooks/binance-pay': typeof ApiPublicWebhooksBinancePayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/copy-trading': typeof CopyTradingRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRouteWithChildren
  '/portfolios': typeof PortfoliosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk': typeof RiskRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/portfolio': typeof AuthenticatedAppPortfolioRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/portal/accounts': typeof AuthenticatedPortalAccountsRoute
  '/_authenticated/portal/activity': typeof AuthenticatedPortalActivityRoute
  '/_authenticated/portal/competitions': typeof AuthenticatedPortalCompetitionsRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/downloads': typeof AuthenticatedPortalDownloadsRoute
  '/_authenticated/portal/favorites': typeof AuthenticatedPortalFavoritesRoute
  '/_authenticated/portal/mfa': typeof AuthenticatedPortalMfaRoute
  '/_authenticated/portal/notifications': typeof AuthenticatedPortalNotificationsRoute
  '/_authenticated/portal/performance': typeof AuthenticatedPortalPerformanceRoute
  '/_authenticated/portal/portfolio': typeof AuthenticatedPortalPortfolioRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/_authenticated/portal/settings': typeof AuthenticatedPortalSettingsRoute
  '/_authenticated/portal/statements': typeof AuthenticatedPortalStatementsRoute
  '/_authenticated/portal/support': typeof AuthenticatedPortalSupportRoute
  '/_authenticated/portal/trading': typeof AuthenticatedPortalTradingRoute
  '/_authenticated/portal/transactions': typeof AuthenticatedPortalTransactionsRoute
  '/_authenticated/portal/updates': typeof AuthenticatedPortalUpdatesRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/_admin/admin/accounting': typeof AuthenticatedAdminAdminAccountingRoute
  '/_authenticated/_admin/admin/analytics': typeof AuthenticatedAdminAdminAnalyticsRoute
  '/_authenticated/_admin/admin/audit': typeof AuthenticatedAdminAdminAuditRoute
  '/_authenticated/_admin/admin/backups': typeof AuthenticatedAdminAdminBackupsRoute
  '/_authenticated/_admin/admin/finance': typeof AuthenticatedAdminAdminFinanceRoute
  '/_authenticated/_admin/admin/invoices': typeof AuthenticatedAdminAdminInvoicesRoute
  '/_authenticated/_admin/admin/kyc': typeof AuthenticatedAdminAdminKycRoute
  '/_authenticated/_admin/admin/live-chat': typeof AuthenticatedAdminAdminLiveChatRoute
  '/_authenticated/_admin/admin/marketing': typeof AuthenticatedAdminAdminMarketingRoute
  '/_authenticated/_admin/admin/monitoring': typeof AuthenticatedAdminAdminMonitoringRoute
  '/_authenticated/_admin/admin/notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/_authenticated/_admin/admin/organizations': typeof AuthenticatedAdminAdminOrganizationsRoute
  '/_authenticated/_admin/admin/partners': typeof AuthenticatedAdminAdminPartnersRoute
  '/_authenticated/_admin/admin/payments': typeof AuthenticatedAdminAdminPaymentsRoute
  '/_authenticated/_admin/admin/roles': typeof AuthenticatedAdminAdminRolesRoute
  '/_authenticated/_admin/admin/search': typeof AuthenticatedAdminAdminSearchRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/_authenticated/_admin/admin/subscriptions': typeof AuthenticatedAdminAdminSubscriptionsRoute
  '/_authenticated/_admin/admin/support': typeof AuthenticatedAdminAdminSupportRoute
  '/_authenticated/_admin/admin/user-roles': typeof AuthenticatedAdminAdminUserRolesRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/competitions/$id/trade': typeof AuthenticatedCompetitionsIdTradeRoute
  '/api/public/webhooks/binance-pay': typeof ApiPublicWebhooksBinancePayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/brand'
    | '/competitions'
    | '/contact'
    | '/copy-trading'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/legal'
    | '/markets'
    | '/portfolios'
    | '/privacy'
    | '/reset-password'
    | '/risk'
    | '/terms'
    | '/app'
    | '/dashboard'
    | '/investor'
    | '/security'
    | '/markets/$symbol'
    | '/app/activity'
    | '/app/portfolio'
    | '/app/profile'
    | '/portal/accounts'
    | '/portal/activity'
    | '/portal/competitions'
    | '/portal/documents'
    | '/portal/downloads'
    | '/portal/favorites'
    | '/portal/mfa'
    | '/portal/notifications'
    | '/portal/performance'
    | '/portal/portfolio'
    | '/portal/profile'
    | '/portal/referrals'
    | '/portal/settings'
    | '/portal/statements'
    | '/portal/support'
    | '/portal/trading'
    | '/portal/transactions'
    | '/portal/updates'
    | '/portal/'
    | '/admin/accounting'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/finance'
    | '/admin/invoices'
    | '/admin/kyc'
    | '/admin/live-chat'
    | '/admin/marketing'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/organizations'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/user-roles'
    | '/admin/users'
    | '/competitions/$id/trade'
    | '/api/public/webhooks/binance-pay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/brand'
    | '/competitions'
    | '/contact'
    | '/copy-trading'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/legal'
    | '/markets'
    | '/portfolios'
    | '/privacy'
    | '/reset-password'
    | '/risk'
    | '/terms'
    | '/app'
    | '/dashboard'
    | '/investor'
    | '/security'
    | '/markets/$symbol'
    | '/app/activity'
    | '/app/portfolio'
    | '/app/profile'
    | '/portal/accounts'
    | '/portal/activity'
    | '/portal/competitions'
    | '/portal/documents'
    | '/portal/downloads'
    | '/portal/favorites'
    | '/portal/mfa'
    | '/portal/notifications'
    | '/portal/performance'
    | '/portal/portfolio'
    | '/portal/profile'
    | '/portal/referrals'
    | '/portal/settings'
    | '/portal/statements'
    | '/portal/support'
    | '/portal/trading'
    | '/portal/transactions'
    | '/portal/updates'
    | '/portal'
    | '/admin/accounting'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backups'
    | '/admin/finance'
    | '/admin/invoices'
    | '/admin/kyc'
    | '/admin/live-chat'
    | '/admin/marketing'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/organizations'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/user-roles'
    | '/admin/users'
    | '/competitions/$id/trade'
    | '/api/public/webhooks/binance-pay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/brand'
    | '/competitions'
    | '/contact'
    | '/copy-trading'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/legal'
    | '/markets'
    | '/portfolios'
    | '/privacy'
    | '/reset-password'
    | '/risk'
    | '/terms'
    | '/_authenticated/_admin'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/investor'
    | '/_authenticated/security'
    | '/markets/$symbol'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/portfolio'
    | '/_authenticated/app/profile'
    | '/_authenticated/portal/accounts'
    | '/_authenticated/portal/activity'
    | '/_authenticated/portal/competitions'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/downloads'
    | '/_authenticated/portal/favorites'
    | '/_authenticated/portal/mfa'
    | '/_authenticated/portal/notifications'
    | '/_authenticated/portal/performance'
    | '/_authenticated/portal/portfolio'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/referrals'
    | '/_authenticated/portal/settings'
    | '/_authenticated/portal/statements'
    | '/_authenticated/portal/support'
    | '/_authenticated/portal/trading'
    | '/_authenticated/portal/transactions'
    | '/_authenticated/portal/updates'
    | '/_authenticated/portal/'
    | '/_authenticated/_admin/admin/accounting'
    | '/_authenticated/_admin/admin/analytics'
    | '/_authenticated/_admin/admin/audit'
    | '/_authenticated/_admin/admin/backups'
    | '/_authenticated/_admin/admin/finance'
    | '/_authenticated/_admin/admin/invoices'
    | '/_authenticated/_admin/admin/kyc'
    | '/_authenticated/_admin/admin/live-chat'
    | '/_authenticated/_admin/admin/marketing'
    | '/_authenticated/_admin/admin/monitoring'
    | '/_authenticated/_admin/admin/notifications'
    | '/_authenticated/_admin/admin/organizations'
    | '/_authenticated/_admin/admin/partners'
    | '/_authenticated/_admin/admin/payments'
    | '/_authenticated/_admin/admin/roles'
    | '/_authenticated/_admin/admin/search'
    | '/_authenticated/_admin/admin/settings'
    | '/_authenticated/_admin/admin/subscriptions'
    | '/_authenticated/_admin/admin/support'
    | '/_authenticated/_admin/admin/user-roles'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/competitions/$id/trade'
    | '/api/public/webhooks/binance-pay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRoute
  CompetitionsRoute: typeof CompetitionsRoute
  ContactRoute: typeof ContactRoute
  CopyTradingRoute: typeof CopyTradingRoute
  EducationRoute: typeof EducationRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalRoute: typeof LegalRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  PortfoliosRoute: typeof PortfoliosRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiskRoute: typeof RiskRoute
  TermsRoute: typeof TermsRoute
  ApiPublicWebhooksBinancePayRoute: typeof ApiPublicWebhooksBinancePayRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-trading': {
      id: '/copy-trading'
      path: '/copy-trading'
      fullPath: '/copy-trading'
      preLoaderRoute: typeof CopyTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$symbol': {
      id: '/markets/$symbol'
      path: '/$symbol'
      fullPath: '/markets/$symbol'
      preLoaderRoute: typeof MarketsSymbolRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/updates': {
      id: '/_authenticated/portal/updates'
      path: '/portal/updates'
      fullPath: '/portal/updates'
      preLoaderRoute: typeof AuthenticatedPortalUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/transactions': {
      id: '/_authenticated/portal/transactions'
      path: '/portal/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof AuthenticatedPortalTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/trading': {
      id: '/_authenticated/portal/trading'
      path: '/portal/trading'
      fullPath: '/portal/trading'
      preLoaderRoute: typeof AuthenticatedPortalTradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/support': {
      id: '/_authenticated/portal/support'
      path: '/portal/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof AuthenticatedPortalSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/statements': {
      id: '/_authenticated/portal/statements'
      path: '/portal/statements'
      fullPath: '/portal/statements'
      preLoaderRoute: typeof AuthenticatedPortalStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/settings': {
      id: '/_authenticated/portal/settings'
      path: '/portal/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof AuthenticatedPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/referrals': {
      id: '/_authenticated/portal/referrals'
      path: '/portal/referrals'
      fullPath: '/portal/referrals'
      preLoaderRoute: typeof AuthenticatedPortalReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/portfolio': {
      id: '/_authenticated/portal/portfolio'
      path: '/portal/portfolio'
      fullPath: '/portal/portfolio'
      preLoaderRoute: typeof AuthenticatedPortalPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/performance': {
      id: '/_authenticated/portal/performance'
      path: '/portal/performance'
      fullPath: '/portal/performance'
      preLoaderRoute: typeof AuthenticatedPortalPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/notifications': {
      id: '/_authenticated/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AuthenticatedPortalNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/mfa': {
      id: '/_authenticated/portal/mfa'
      path: '/portal/mfa'
      fullPath: '/portal/mfa'
      preLoaderRoute: typeof AuthenticatedPortalMfaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/favorites': {
      id: '/_authenticated/portal/favorites'
      path: '/portal/favorites'
      fullPath: '/portal/favorites'
      preLoaderRoute: typeof AuthenticatedPortalFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/downloads': {
      id: '/_authenticated/portal/downloads'
      path: '/portal/downloads'
      fullPath: '/portal/downloads'
      preLoaderRoute: typeof AuthenticatedPortalDownloadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/portal/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/competitions': {
      id: '/_authenticated/portal/competitions'
      path: '/portal/competitions'
      fullPath: '/portal/competitions'
      preLoaderRoute: typeof AuthenticatedPortalCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/activity': {
      id: '/_authenticated/portal/activity'
      path: '/portal/activity'
      fullPath: '/portal/activity'
      preLoaderRoute: typeof AuthenticatedPortalActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/accounts': {
      id: '/_authenticated/portal/accounts'
      path: '/portal/accounts'
      fullPath: '/portal/accounts'
      preLoaderRoute: typeof AuthenticatedPortalAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/portfolio': {
      id: '/_authenticated/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AuthenticatedAppPortfolioRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/binance-pay': {
      id: '/api/public/webhooks/binance-pay'
      path: '/api/public/webhooks/binance-pay'
      fullPath: '/api/public/webhooks/binance-pay'
      preLoaderRoute: typeof ApiPublicWebhooksBinancePayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/competitions/$id/trade': {
      id: '/_authenticated/competitions/$id/trade'
      path: '/competitions/$id/trade'
      fullPath: '/competitions/$id/trade'
      preLoaderRoute: typeof AuthenticatedCompetitionsIdTradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/user-roles': {
      id: '/_authenticated/_admin/admin/user-roles'
      path: '/admin/user-roles'
      fullPath: '/admin/user-roles'
      preLoaderRoute: typeof AuthenticatedAdminAdminUserRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/support': {
      id: '/_authenticated/_admin/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/subscriptions': {
      id: '/_authenticated/_admin/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/search': {
      id: '/_authenticated/_admin/admin/search'
      path: '/admin/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AuthenticatedAdminAdminSearchRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/roles': {
      id: '/_authenticated/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/payments': {
      id: '/_authenticated/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/partners': {
      id: '/_authenticated/_admin/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/organizations': {
      id: '/_authenticated/_admin/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/notifications': {
      id: '/_authenticated/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/monitoring': {
      id: '/_authenticated/_admin/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/marketing': {
      id: '/_authenticated/_admin/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/live-chat': {
      id: '/_authenticated/_admin/admin/live-chat'
      path: '/admin/live-chat'
      fullPath: '/admin/live-chat'
      preLoaderRoute: typeof AuthenticatedAdminAdminLiveChatRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/kyc': {
      id: '/_authenticated/_admin/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/invoices': {
      id: '/_authenticated/_admin/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/finance': {
      id: '/_authenticated/_admin/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/backups': {
      id: '/_authenticated/_admin/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthenticatedAdminAdminBackupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/audit': {
      id: '/_authenticated/_admin/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/analytics': {
      id: '/_authenticated/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/accounting': {
      id: '/_authenticated/_admin/admin/accounting'
      path: '/admin/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AuthenticatedAdminAdminAccountingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminAccountingRoute: typeof AuthenticatedAdminAdminAccountingRoute
  AuthenticatedAdminAdminAnalyticsRoute: typeof AuthenticatedAdminAdminAnalyticsRoute
  AuthenticatedAdminAdminAuditRoute: typeof AuthenticatedAdminAdminAuditRoute
  AuthenticatedAdminAdminBackupsRoute: typeof AuthenticatedAdminAdminBackupsRoute
  AuthenticatedAdminAdminFinanceRoute: typeof AuthenticatedAdminAdminFinanceRoute
  AuthenticatedAdminAdminInvoicesRoute: typeof AuthenticatedAdminAdminInvoicesRoute
  AuthenticatedAdminAdminKycRoute: typeof AuthenticatedAdminAdminKycRoute
  AuthenticatedAdminAdminLiveChatRoute: typeof AuthenticatedAdminAdminLiveChatRoute
  AuthenticatedAdminAdminMarketingRoute: typeof AuthenticatedAdminAdminMarketingRoute
  AuthenticatedAdminAdminMonitoringRoute: typeof AuthenticatedAdminAdminMonitoringRoute
  AuthenticatedAdminAdminNotificationsRoute: typeof AuthenticatedAdminAdminNotificationsRoute
  AuthenticatedAdminAdminOrganizationsRoute: typeof AuthenticatedAdminAdminOrganizationsRoute
  AuthenticatedAdminAdminPartnersRoute: typeof AuthenticatedAdminAdminPartnersRoute
  AuthenticatedAdminAdminPaymentsRoute: typeof AuthenticatedAdminAdminPaymentsRoute
  AuthenticatedAdminAdminRolesRoute: typeof AuthenticatedAdminAdminRolesRoute
  AuthenticatedAdminAdminSearchRoute: typeof AuthenticatedAdminAdminSearchRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminSubscriptionsRoute: typeof AuthenticatedAdminAdminSubscriptionsRoute
  AuthenticatedAdminAdminSupportRoute: typeof AuthenticatedAdminAdminSupportRoute
  AuthenticatedAdminAdminUserRolesRoute: typeof AuthenticatedAdminAdminUserRolesRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminAccountingRoute:
      AuthenticatedAdminAdminAccountingRoute,
    AuthenticatedAdminAdminAnalyticsRoute:
      AuthenticatedAdminAdminAnalyticsRoute,
    AuthenticatedAdminAdminAuditRoute: AuthenticatedAdminAdminAuditRoute,
    AuthenticatedAdminAdminBackupsRoute: AuthenticatedAdminAdminBackupsRoute,
    AuthenticatedAdminAdminFinanceRoute: AuthenticatedAdminAdminFinanceRoute,
    AuthenticatedAdminAdminInvoicesRoute: AuthenticatedAdminAdminInvoicesRoute,
    AuthenticatedAdminAdminKycRoute: AuthenticatedAdminAdminKycRoute,
    AuthenticatedAdminAdminLiveChatRoute: AuthenticatedAdminAdminLiveChatRoute,
    AuthenticatedAdminAdminMarketingRoute:
      AuthenticatedAdminAdminMarketingRoute,
    AuthenticatedAdminAdminMonitoringRoute:
      AuthenticatedAdminAdminMonitoringRoute,
    AuthenticatedAdminAdminNotificationsRoute:
      AuthenticatedAdminAdminNotificationsRoute,
    AuthenticatedAdminAdminOrganizationsRoute:
      AuthenticatedAdminAdminOrganizationsRoute,
    AuthenticatedAdminAdminPartnersRoute: AuthenticatedAdminAdminPartnersRoute,
    AuthenticatedAdminAdminPaymentsRoute: AuthenticatedAdminAdminPaymentsRoute,
    AuthenticatedAdminAdminRolesRoute: AuthenticatedAdminAdminRolesRoute,
    AuthenticatedAdminAdminSearchRoute: AuthenticatedAdminAdminSearchRoute,
    AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
    AuthenticatedAdminAdminSubscriptionsRoute:
      AuthenticatedAdminAdminSubscriptionsRoute,
    AuthenticatedAdminAdminSupportRoute: AuthenticatedAdminAdminSupportRoute,
    AuthenticatedAdminAdminUserRolesRoute:
      AuthenticatedAdminAdminUserRolesRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppPortfolioRoute: typeof AuthenticatedAppPortfolioRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppPortfolioRoute: AuthenticatedAppPortfolioRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedPortalAccountsRoute: typeof AuthenticatedPortalAccountsRoute
  AuthenticatedPortalActivityRoute: typeof AuthenticatedPortalActivityRoute
  AuthenticatedPortalCompetitionsRoute: typeof AuthenticatedPortalCompetitionsRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalDownloadsRoute: typeof AuthenticatedPortalDownloadsRoute
  AuthenticatedPortalFavoritesRoute: typeof AuthenticatedPortalFavoritesRoute
  AuthenticatedPortalMfaRoute: typeof AuthenticatedPortalMfaRoute
  AuthenticatedPortalNotificationsRoute: typeof AuthenticatedPortalNotificationsRoute
  AuthenticatedPortalPerformanceRoute: typeof AuthenticatedPortalPerformanceRoute
  AuthenticatedPortalPortfolioRoute: typeof AuthenticatedPortalPortfolioRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalReferralsRoute: typeof AuthenticatedPortalReferralsRoute
  AuthenticatedPortalSettingsRoute: typeof AuthenticatedPortalSettingsRoute
  AuthenticatedPortalStatementsRoute: typeof AuthenticatedPortalStatementsRoute
  AuthenticatedPortalSupportRoute: typeof AuthenticatedPortalSupportRoute
  AuthenticatedPortalTradingRoute: typeof AuthenticatedPortalTradingRoute
  AuthenticatedPortalTransactionsRoute: typeof AuthenticatedPortalTransactionsRoute
  AuthenticatedPortalUpdatesRoute: typeof AuthenticatedPortalUpdatesRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedCompetitionsIdTradeRoute: typeof AuthenticatedCompetitionsIdTradeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedPortalAccountsRoute: AuthenticatedPortalAccountsRoute,
  AuthenticatedPortalActivityRoute: AuthenticatedPortalActivityRoute,
  AuthenticatedPortalCompetitionsRoute: AuthenticatedPortalCompetitionsRoute,
  AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
  AuthenticatedPortalDownloadsRoute: AuthenticatedPortalDownloadsRoute,
  AuthenticatedPortalFavoritesRoute: AuthenticatedPortalFavoritesRoute,
  AuthenticatedPortalMfaRoute: AuthenticatedPortalMfaRoute,
  AuthenticatedPortalNotificationsRoute: AuthenticatedPortalNotificationsRoute,
  AuthenticatedPortalPerformanceRoute: AuthenticatedPortalPerformanceRoute,
  AuthenticatedPortalPortfolioRoute: AuthenticatedPortalPortfolioRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalReferralsRoute: AuthenticatedPortalReferralsRoute,
  AuthenticatedPortalSettingsRoute: AuthenticatedPortalSettingsRoute,
  AuthenticatedPortalStatementsRoute: AuthenticatedPortalStatementsRoute,
  AuthenticatedPortalSupportRoute: AuthenticatedPortalSupportRoute,
  AuthenticatedPortalTradingRoute: AuthenticatedPortalTradingRoute,
  AuthenticatedPortalTransactionsRoute: AuthenticatedPortalTransactionsRoute,
  AuthenticatedPortalUpdatesRoute: AuthenticatedPortalUpdatesRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedCompetitionsIdTradeRoute: AuthenticatedCompetitionsIdTradeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketsRouteChildren {
  MarketsSymbolRoute: typeof MarketsSymbolRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsSymbolRoute: MarketsSymbolRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRoute,
  CompetitionsRoute: CompetitionsRoute,
  ContactRoute: ContactRoute,
  CopyTradingRoute: CopyTradingRoute,
  EducationRoute: EducationRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalRoute: LegalRoute,
  MarketsRoute: MarketsRouteWithChildren,
  PortfoliosRoute: PortfoliosRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiskRoute: RiskRoute,
  TermsRoute: TermsRoute,
  ApiPublicWebhooksBinancePayRoute: ApiPublicWebhooksBinancePayRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
