
-- Partition market_data_ticks and market_data_candles by time; both are empty today.

-- ============ market_data_ticks ============
DROP TABLE public.market_data_ticks;

CREATE TABLE public.market_data_ticks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  symbol        text NOT NULL,
  provider_code text NOT NULL,
  price         numeric(20,8) NOT NULL,
  volume        numeric(24,4),
  price_time    timestamptz NOT NULL,
  received_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, price_time)
) PARTITION BY RANGE (price_time);

CREATE INDEX idx_mdt_symbol_time   ON public.market_data_ticks (symbol, price_time DESC);
CREATE INDEX idx_mdt_provider_time ON public.market_data_ticks (provider_code, price_time DESC);

GRANT SELECT ON public.market_data_ticks TO authenticated;
GRANT ALL    ON public.market_data_ticks TO service_role;

ALTER TABLE public.market_data_ticks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "ticks readable by authenticated" ON public.market_data_ticks
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "ticks writable by admin" ON public.market_data_ticks
  TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));

CREATE TRIGGER trg_validate_market_tick
  BEFORE INSERT ON public.market_data_ticks
  FOR EACH ROW EXECUTE FUNCTION public.validate_market_data_tick();

-- ============ market_data_candles ============
DROP TABLE public.market_data_candles;

CREATE TABLE public.market_data_candles (
  id            uuid NOT NULL DEFAULT gen_random_uuid(),
  symbol        text NOT NULL,
  provider_code text NOT NULL,
  timeframe     text NOT NULL CHECK (timeframe = ANY (ARRAY['1m','5m','15m','30m','1H','4H','1D','1W','1M'])),
  bucket_start  timestamptz NOT NULL,
  open          numeric(20,8) NOT NULL,
  high          numeric(20,8) NOT NULL,
  low           numeric(20,8) NOT NULL,
  close         numeric(20,8) NOT NULL,
  volume        numeric(24,4) DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, bucket_start),
  UNIQUE (symbol, provider_code, timeframe, bucket_start)
) PARTITION BY RANGE (bucket_start);

CREATE INDEX idx_mdc_symbol_tf_time ON public.market_data_candles (symbol, timeframe, bucket_start DESC);
CREATE INDEX idx_mdc_provider       ON public.market_data_candles (provider_code);

GRANT SELECT ON public.market_data_candles TO anon, authenticated;
GRANT ALL    ON public.market_data_candles TO service_role;

ALTER TABLE public.market_data_candles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "candles readable" ON public.market_data_candles
  FOR SELECT USING (true);
CREATE POLICY "candles writable by admin" ON public.market_data_candles
  TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));

CREATE TRIGGER trg_mdc_updated_at
  BEFORE UPDATE ON public.market_data_candles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============ Retention: drop old partitions ============
CREATE OR REPLACE FUNCTION public.md_drop_old_partitions(
  p_parent text,
  p_retention interval
) RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r          record;
  v_cutoff   timestamptz := now() - p_retention;
  v_upper    timestamptz;
  v_bound    text;
  v_dropped  int := 0;
BEGIN
  FOR r IN
    SELECT c.oid, n.nspname, c.relname
      FROM pg_inherits i
      JOIN pg_class p       ON p.oid = i.inhparent
      JOIN pg_namespace pn  ON pn.oid = p.relnamespace
      JOIN pg_class c       ON c.oid = i.inhrelid
      JOIN pg_namespace n   ON n.oid = c.relnamespace
     WHERE pn.nspname = 'public' AND p.relname = p_parent
  LOOP
    v_bound := pg_get_expr(
      (SELECT relpartbound FROM pg_class WHERE oid = r.oid),
      r.oid
    );
    -- expected form: FOR VALUES FROM ('...') TO ('YYYY-MM-DD ...')
    v_upper := (regexp_match(v_bound, 'TO \(''([^'']+)''\)'))[1]::timestamptz;
    IF v_upper IS NOT NULL AND v_upper <= v_cutoff THEN
      EXECUTE format('DROP TABLE IF EXISTS %I.%I', r.nspname, r.relname);
      v_dropped := v_dropped + 1;
    END IF;
  END LOOP;
  RETURN v_dropped;
END $$;

-- ============ Maintenance: ensure partitions + retention ============
CREATE OR REPLACE FUNCTION public.md_maintain_partitions()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticks_created   int;
  v_candles_created int;
  v_ticks_dropped   int;
  v_candles_dropped int;
BEGIN
  -- ensure current + 3 months ahead, 1 behind
  v_ticks_created   := public.hyperscale_ensure_monthly_partitions('market_data_ticks',   3, 1);
  v_candles_created := public.hyperscale_ensure_monthly_partitions('market_data_candles', 3, 1);

  -- retention: ticks 30 days, candles 365 days
  v_ticks_dropped   := public.md_drop_old_partitions('market_data_ticks',   interval '30 days');
  v_candles_dropped := public.md_drop_old_partitions('market_data_candles', interval '365 days');

  RETURN jsonb_build_object(
    'ticks_created',   v_ticks_created,
    'candles_created', v_candles_created,
    'ticks_dropped',   v_ticks_dropped,
    'candles_dropped', v_candles_dropped,
    'ran_at',          now()
  );
END $$;

-- Bootstrap initial partitions so ingestion works immediately.
SELECT public.hyperscale_ensure_monthly_partitions('market_data_ticks',   3, 1);
SELECT public.hyperscale_ensure_monthly_partitions('market_data_candles', 3, 1);

-- ============ Schedule maintenance daily via pg_cron ============
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('md_maintain_partitions_daily')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'md_maintain_partitions_daily');
    PERFORM cron.schedule(
      'md_maintain_partitions_daily',
      '15 3 * * *',
      $CRON$ SELECT public.md_maintain_partitions(); $CRON$
    );
  END IF;
END $$;

-- Trim cleanup_expired_data: partition drops now handle tick retention.
CREATE OR REPLACE FUNCTION public.cleanup_expired_data()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_inv int := 0;
  v_gi  int := 0;
  v_lat int := 0;
BEGIN
  DELETE FROM public.comp_invitations
   WHERE created_at < now() - INTERVAL '30 days'
     AND (used_at IS NULL OR used_at < now() - INTERVAL '60 days');
  GET DIAGNOSTICS v_inv = ROW_COUNT;

  DELETE FROM public.guest_inquiries
   WHERE created_at < now() - INTERVAL '90 days'
     AND status IN ('closed', 'resolved', 'archived');
  GET DIAGNOSTICS v_gi = ROW_COUNT;

  DELETE FROM public.market_data_latency_samples
   WHERE created_at < now() - INTERVAL '14 days';
  GET DIAGNOSTICS v_lat = ROW_COUNT;

  RETURN jsonb_build_object(
    'invitations', v_inv, 'guest_inquiries', v_gi,
    'latency_samples', v_lat,
    'note', 'market_data ticks/candles retention handled by md_maintain_partitions'
  );
EXCEPTION WHEN undefined_column OR undefined_table THEN
  RETURN jsonb_build_object('warning', SQLERRM);
END;
$function$;
